development:
  adapter: postgresql
  encoding: unicode
  database: school-system-test_development
  pool: 5
  username: postgres
  password:
  host: localhost
  encoding: utf8

test:
  adapter: postgresql
  encoding: unicode
  database: school-system-test_test
  pool: 5
  username: postgres
  password:
  min_messages: WARNING
  host: localhost
  encoding: utf8